name: Switch Node version
on: 
  pull_request:

jobs:
  run-npm-test:
    runs-on: ubuntu-latest
    steps:
        - name: Set the node value
          id: step_one
          run: |
            echo "NODE_VERSION=14" >> $GITHUB_ENV
        - name: checkout
          uses: actions/checkout@v2
        - name : setup node
          uses: actions/setup-node@v2
          with:
            node-version: '${{ env.NODE_VERSION }}'
        - name: verify node version
          shell: bash
          run: |
            echo $(node -v)
        - name: run test
          shell: bash
          run: |
            npm install
            npm test